version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_NAME=elden_ring
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./src:/app
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=elden_ring
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: 